### ISSUE TITLE
Is the music supposed to play when you open the application?

### ISSUE THREAD

**Issue by keanedawg** [alanxoc3/pygame-asteroids#1]
If so, I can't hear it, which I think might mean I'm lacking some necessary library?

**Comment by alanxoc3** [comment]
Thanks and why are you awake?

**Comment by keanedawg** [comment]
idk. why are you?

**Comment by alanxoc3** [comment]
Uuu homework

**Comment by alanxoc3** [comment]
Oh the music isn't supposed to play.

**Comment by keanedawg** [comment]
Nice. I'm just kinda up I guess. I don't have anything critically due, but I'm trying to work on it

**Comment by alanxoc3** [comment]
I just found cool songs

**Comment by keanedawg** [comment]
oh ok

**Comment by keanedawg** [comment]
yeah the songs are great though. like perfectly fitting IMO.

**Comment by keanedawg** [comment]
I was gonna suggest this, but I guess ur music is alright

https://www.youtube.com/watch?v=UQ13nr6urIo

**Comment by alanxoc3** [comment]
Cool. To make sound play it's something really simple like pygame.audio.load then play. Look at the pygame api

**Comment by alanxoc3** [comment]
That song would have been cool too. Besides most of it.

**Comment by keanedawg** [comment]
hahahaha
