### ISSUE TITLE
Yo bb, you free 2nite?

### ISSUE THREAD

**Issue by keanedawg** [alanxoc3/pygame-asteroids#2]

**Comment by alanxoc3** [comment]
Well, I shouldn't be, because of homework... But... I can be.

**Comment by keanedawg** [comment]
nah bb. you can keep working ;)

I might make some progress on it. You can always call me

**Comment by alanxoc3** [comment]
Yeah, I won't be able to work on it tonight for sure now. Gotta get stuff done.
